### ISSUE TITLE
Ionic relaxation dataset

### ISSUE THREAD

**Issue by tanooj-s** [google-deepmind/materials_discovery#10]
Hello, I wanted to ask if the ionic relaxation dataset is going to be made available for the community to test out anytime soon. If I understand the claims made in the publication correctly, the ionic relaxation data is sufficient to train a machine-learned potential that generalizes to all sorts of out-of-distribution configurations. The community currently spends a lot of effort (and queue time on clusters) running AIMD simulations to generate training data, so it would be extremely beneficial to have this dataset available in order to run larger/longer simulations for predictions of material properties.

**Comment by tanooj-s** [comment]
bump to check whether this (and the other open issues) should expect to get a response anytime soon

**Comment by linnlii** [comment]
Just wondering if the authors have responded to this issue. I'm also interested in the ionic relaxation dataset.
